### ISSUE TITLE
Transliteration based on source language

### ISSUE THREAD

**Issue by brusch** [Behat/Transliterator#10]
Currently the transliteration is not based on the source language of the text, but this makes a big difference in some cases.
Following some examples: 

'Ä' (U+00C4) transliterates to 'A' but when the source text is in German should transliterate to 'Ae'

There are many more examples: 
https://github.com/pimcore/pimcore/blob/master/pimcore/lib/Pimcore/Tool/Transliteration/Data/x00.php#L25

Would be cool to have this integrated.

**Comment by acrozes** [comment]
An other sample in French: "l'eau" => "l-eau"

**Comment by stof** [comment]
For locale-aware transliteration, I suggest using the `Transliterator` class available in ext-intl.
