### ISSUE TITLE
New release with updated Perl Text-Unidecode commit

### ISSUE THREAD

**Issue by FaaPz** [Behat/Transliterator#17]
Could you release a new version with the latest commits?

We would like to use this package, but we need the following commit:
- _Updated to version 1.27 of Perl Unidecode_ (8732e225c7a450f9ed657bd158e6487463800867)

Thank you in advance!

**Comment by danielstjules** [comment]
@stof A new release would be greatly appreciated :)

**Comment by willemstuursma** [comment]
@stof anything we can do to help here? We'd love a new version.

**Comment by willemstuursma** [comment]
Thanks @everzet!
