### ISSUE TITLE
Incorrect translating Russian letter 'е' to 'ie'

### ISSUE THREAD

**Issue by bocharsky-bw** [Behat/Transliterator#4]
**Expected Result**:
`е` => `e` (`тест` => `test`)

**Actual Result**:
 `е` => `ie` (`тест` => `tiest`)

P.S. Google transliterate as [test](https://translate.google.com/#ru/en/%D1%82%D0%B5%D1%81%D1%82)

**Comment by sunra** [comment]
+1

**Comment by stof** [comment]
This was fixed in https://github.com/Behat/Transliterator/pull/12
